---
version: "3"
services:
  clickhouse:
    image: yandex/clickhouse-server:21.7-alpine
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8123:8123"
    volumes:
      - "clickhouse:/var/lib/clickhouse"
    ulimits:
      nofile: 262144

volumes:
  clickhouse:
