[package]
name = "servicegraph-api"
version = "0.1.0"
edition = "2018"


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clickhouse-rs = "0.1.21"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
