[package]
name = "servicegraph-api"
version = "0.1.0"
edition = "2018"


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "0.8", features = ["v4"] }

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]