[development]
address = "localhost"
port = 8000
workers = 2
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 8
log = "critical"
limits = { forms = 32768 }
