const colors = {
  // EDGES AND NODES SELECTED STATE
  SELECTED: "#aa0000",
  SELECTED_BORDER: "#330000",

  // NODES
  TRANSACTION_NODE_BG: "#888",
  TRANSACTION_NODE_BORDER: "black",
  TRANSACTION_NODE_BG_SELECTED: "black",
  SERVICE_NODE_BG: "white",
  SERVICE_NODE_BORDER: "black",
  SERVICE_NODE_BG_SELECTED: "#ddd",
  NODE_UNHEALTHY_BG: "#f18a92",
  NODE_UNHEALTHY_BORDER: "#FF0000",
  INACTIVE_NODE: "#eeeeee",

  // EDGES
  EDGE_HEALTHY: "#888",
  EDGE_UNHEALTHY: "#ffbdb4",
  EDGE_HEALTHY_SELECTED: "black",
  EDGE_UNHEALTHY_SELECTED: "red"
};

export default colors;
